// Generated by Wrangler. Run `wrangler types` to regenerate.
// After running `pnpm install && pnpm types`, this file will be replaced
// with the full generated types for your worker bindings.

interface Env {
  // Add your bindings here, e.g.:
  // MY_KV: KVNamespace;
  // MY_DB: D1Database;
  // MY_DO: DurableObjectNamespace;
}
